// AUTO-GENERATED from HeadRush Prime (categoryOfBlock) — Prime fw 5.0.1.
// Regenerate if the Prime firmware reorders ModuleTypes. See docs/UX_MODEL.md.
#pragma once
#include <Arduino.h>

// Generic block categories (the 20 device categories collapsed to the set the
// knob-default generator reasons about).
enum BlockCat : uint8_t {
    BC_NONE = 0,
    BC_AMP = 1,
    BC_CAB = 2,
    BC_CLONE = 3,
    BC_VOCAL = 4,
    BC_DRIVE = 5,
    BC_EQ = 6,
    BC_COMP = 7,
    BC_DELAY = 8,
    BC_REVERB = 9,
    BC_MOD = 10,
    BC_FILTER = 11,
    BC_PITCH = 12,
    BC_DYN = 13,
    BC_RHY = 14,
    BC_SYNTH = 15,
    BC_UTIL = 16,
    BC_FXLOOP = 17,
    BC_COUNT
};

static constexpr int MODULE_TYPE_COUNT = 272;

// ModuleType index -> generic category. Index matches Chain.ModuleTypeN.
const uint8_t MODULE_CATEGORY[MODULE_TYPE_COUNT] PROGMEM = {
     0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
     3, 3, 3, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5,
     5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6,
     6, 6, 6, 6, 6, 6, 6, 9, 9, 9, 9, 9, 9,13,13, 7,
     7,16,16,16,16, 8, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5,
     5, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6,11,11,10,10,10,
    10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,
    10,10,10,10,10,10,10, 8, 8, 8, 8, 8, 8, 8, 8, 8,
     8, 9, 9,11,11,11,11,11,11,11,11,12,12,12,12,10,
    10,12,12,12,12,11,11,12,12,11,11, 8, 8,13,13,10,
    10, 8, 8, 9, 9,12,12,12,12,12,12,13,13, 8, 8,10,
    10,12,12,13,13,13,13, 9, 9, 9, 9,14,14,14,14, 8,
     8, 8, 8, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5,
     5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5,10,10,10,
    10,10,10, 8, 8,11,11,10,10, 8, 8, 5, 5,10,10,10,
    10,10,10, 8, 8, 6, 6,16,16, 9, 9,15,15,15,15,15,
    15, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,17,
};

// ModuleType index -> block object name (path = name with " "/"/" -> "_").
const char* const MODULE_NAME[MODULE_TYPE_COUNT] PROGMEM = {
    "Empty Slot",
    "Amp",
    "Amp 2",
    "ReValver Amp",
    "ReValver Amp 2",
    "ReValver Cab",
    "ReValver Cab 2",
    "Cab",
    "Cab 2",
    "IR",
    "IR 2",
    "IR (1024)",
    "IR (1024) 2",
    "Amp Clone",
    "Amp Clone 2",
    "Pedal Clone",
    "Pedal Clone 2",
    "SuperClone",
    "SuperClone 2",
    "Gray Comp",
    "Gray Comp 2",
    "DynIII Comp",
    "DynIII Comp 2",
    "Green JRC-OD",
    "Green JRC-OD 2",
    "White Boost",
    "White Boost 2",
    "Jimmy OD",
    "Jimmy OD 2",
    "Palace OD",
    "Palace OD 2",
    "Tri Fuzz",
    "Tri Fuzz 2",
    "B Dist 7000",
    "B Dist 7000 2",
    "Glorious Drive",
    "Glorious Drive 2",
    "B2 Drive",
    "B2 Drive 2",
    "D250 Drive",
    "D250 Drive 2",
    "Round Fuzz",
    "Round Fuzz 2",
    "K Drive",
    "K Drive 2",
    "Black Op",
    "Black Op 2",
    "Bass EQ",
    "Bass EQ 2",
    "Graphic EQ",
    "Graphic EQ 2",
    "Ten Freq EQ",
    "Ten Freq EQ 2",
    "Para EQ",
    "Para EQ 2",
    "AIR Reverb",
    "AIR Reverb 2",
    "Eleven Reverb",
    "Eleven Reverb 2",
    "Spring Reverb",
    "Spring Reverb 2",
    "Volume",
    "Volume 2",
    "Side Comp",
    "Side Comp 2",
    "Noise Filter",
    "Noise Filter 2",
    "Gate",
    "Gate 2",
    "Stereo Doubler",
    "Stereo Doubler 2",
    "Oct Fuzz",
    "Oct Fuzz 2",
    "Anxiety OD",
    "Anxiety OD 2",
    "Anxiety OD V2",
    "Anxiety OD V2 2",
    "D1 Dist",
    "D1 Dist 2",
    "S1 Drive",
    "S1 Drive 2",
    "MX Dist",
    "MX Dist 2",
    "Acoust Sim",
    "Acoust Sim 2",
    "DC Distort",
    "DC Distort 2",
    "8-Bit Crush",
    "8-Bit Crush 2",
    "Acoustic Pre",
    "Acoustic Pre 2",
    "AIR Filter",
    "AIR Filter 2",
    "Chorus",
    "Chorus 2",
    "Multi Chorus",
    "Multi Chorus 2",
    "Dim Chorus",
    "Dim Chorus 2",
    "Flanger",
    "Flanger 2",
    "AIR Flanger",
    "AIR Flanger 2",
    "Vibe Phaser",
    "Vibe Phaser 2",
    "Orange Phaser",
    "Orange Phaser 2",
    "Tron Phaser",
    "Tron Phaser 2",
    "Stone Phaser",
    "Stone Phaser 2",
    "Vibrato",
    "Vibrato 2",
    "Rotary",
    "Rotary 2",
    "Tremolo",
    "Tremolo 2",
    "AIR Vibrato",
    "AIR Vibrato 2",
    "Tape Echo",
    "Tape Echo 2",
    "Time Warp",
    "Time Warp 2",
    "Reverse Delay",
    "Reverse Delay 2",
    "BBD Delay",
    "BBD Delay 2",
    "Dyn Delay",
    "Dyn Delay 2",
    "Spring Guru",
    "Spring Guru 2",
    "Shine Wah",
    "Shine Wah 2",
    "Black Wah",
    "Black Wah 2",
    "More Wah",
    "More Wah 2",
    "White Bass Wah",
    "White Bass Wah 2",
    "Wham",
    "Wham 2",
    "Harm",
    "Harm 2",
    "Panner",
    "Panner 2",
    "Octaves",
    "Octaves 2",
    "Octaves Up",
    "Octaves Up 2",
    "Tron Filter",
    "Tron Filter 2",
    "Smart Harm",
    "Smart Harm 2",
    "Env Filter",
    "Env Filter 2",
    "Reso Delay",
    "Reso Delay 2",
    "Auto Swell",
    "Auto Swell 2",
    "Ring Mod",
    "Ring Mod 2",
    "AIR Delay",
    "AIR Delay 2",
    "Shimmer",
    "Shimmer 2",
    "Chord Wham",
    "Chord Wham 2",
    "Drop Tune",
    "Drop Tune 2",
    "Up Tune",
    "Up Tune 2",
    "Feedback",
    "Feedback 2",
    "Pitch Delay",
    "Pitch Delay 2",
    "Detune",
    "Detune 2",
    "12 String",
    "12 String 2",
    "Sustain",
    "Sustain 2",
    "Hold",
    "Hold 2",
    "Ambi Verb",
    "Ambi Verb 2",
    "Party Verb",
    "Party Verb 2",
    "Kill Seq",
    "Kill Seq 2",
    "Splicer",
    "Splicer 2",
    "Multi Delay",
    "Multi Delay 2",
    "Grain Delay",
    "Grain Delay 2",
    "Pressor",
    "Pressor 2",
    "Slammer",
    "Slammer 2",
    "Budda Comp",
    "Budda Comp 2",
    "Slab O Meat",
    "Slab O Meat 2",
    "Black Death",
    "Black Death 2",
    "Grinder Bass OD",
    "Grinder Bass OD 2",
    "Budda OM OD",
    "Budda OM OD 2",
    "Greener",
    "Greener 2",
    "Greener Lite",
    "Greener Lite 2",
    "Sher'ff",
    "Sher'ff 2",
    "Promise EQ",
    "Promise EQ 2",
    "G EQ",
    "G EQ 2",
    "Treble Booster",
    "Treble Booster 2",
    "Analog Flanger",
    "Analog Flanger 2",
    "Digital Flanger",
    "Digital Flanger 2",
    "Square-Phase",
    "Square-Phase 2",
    "Again Delay",
    "Again Delay 2",
    "Bud Wah",
    "Bud Wah 2",
    "Budda Karma Chorus",
    "Budda Karma Chorus 2",
    "Budda Samsara Delay",
    "Budda Samsara Delay 2",
    "Budda ZenMan",
    "Budda ZenMan 2",
    "C2 Bass Chorus",
    "C2 Bass Chorus 2",
    "Tube Tremolo",
    "Tube Tremolo 2",
    "C2 Chorus",
    "C2 Chorus 2",
    "M104 Analog Delay",
    "M104 Analog Delay 2",
    "Auto Q 8 Band EQ",
    "Auto Q 8 Band EQ 2",
    "Kaften Gate",
    "Kaften Gate 2",
    "C-Verb",
    "C-Verb 2",
    "Hybrid",
    "Hybrid 2",
    "DB-33",
    "DB-33 2",
    "Electric",
    "Electric 2",
    "Vocal Harmony",
    "Vocal Harmony 2",
    "Auto-Tune",
    "Auto-Tune 2",
    "Vocal Doubler",
    "Vocal Doubler 2",
    "Vocal Stutter",
    "Vocal Stutter 2",
    "Vocal Distortion",
    "Vocal Distortion 2",
    "Vocoder",
    "Vocoder 2",
    "De-Esser",
    "De-Esser 2",
    "FX-Loop",
};

inline BlockCat moduleCategory(int idx) {
    if (idx < 0 || idx >= MODULE_TYPE_COUNT) return BC_NONE;
    return (BlockCat)pgm_read_byte(&MODULE_CATEGORY[idx]);
}

// Build "/Evil/Engine/Patch/<name>" for a module index (spaces/slash -> _).
inline String moduleBlockPath(int idx) {
    if (idx <= 0 || idx >= MODULE_TYPE_COUNT) return String();
    String n = (const char*)pgm_read_ptr(&MODULE_NAME[idx]);
    if (n == "Empty Slot") return String();
    for (size_t i = 0; i < n.length(); ++i) { char c = n[i]; if (c == ' ' || c == '/') n[i] = '_'; }
    return String("/Evil/Engine/Patch/") + n;
}

// --- Per-category knob default ("the primary param to ride") ----------------
//
// For a generic category we expose ONE primary parameter on the dial. Blocks in
// a category aren't identical, so each category carries an ordered list of
// candidate prop names; the resolver picks the first the actual block exposes.
// Almost every "amount" param is normalized 0..1 on the wire and shown 0..100%
// (verified against object-meta: Drive/Mix/GainA/Sustain all min=0 max=100
// "%.0f %%"), so one display spec covers them. See docs/UX_MODEL.md §6.

struct CatBindSpec {
    BlockCat cat;
    const char* label;            // on-screen label for the dial
    const char* candidates[4];    // ordered prop names; first present on the block wins
};

// Only the categories the default generator can put on a dial. Order within a
// list is the preference; nullptr terminates.
const CatBindSpec CAT_BIND[] = {
    { BC_DRIVE,  "DRIVE",  { "Drive", "Gain", "Level", nullptr } },
    { BC_AMP,    "GAIN",   { "GainA", "Master", nullptr, nullptr } },
    { BC_COMP,   "COMP",   { "Sustain", "Level", nullptr, nullptr } },
    { BC_REVERB, "REVERB", { "Mix", nullptr, nullptr, nullptr } },
    { BC_DELAY,  "DELAY",  { "Mix", "Feedback", nullptr, nullptr } },
    { BC_MOD,    "MOD",    { "Mix", "Depth", "Rate", nullptr } },
    { BC_FILTER, "FILTER", { "Freq", "Mix", nullptr, nullptr } },
    { BC_PITCH,  "PITCH",  { "Mix", nullptr, nullptr, nullptr } },
};
const int CAT_BIND_COUNT = sizeof(CAT_BIND) / sizeof(CAT_BIND[0]);

inline const CatBindSpec* catBindSpec(BlockCat c) {
    for (int i = 0; i < CAT_BIND_COUNT; ++i) if (CAT_BIND[i].cat == c) return &CAT_BIND[i];
    return nullptr;
}

// The two complementary buckets for the default dials 2 & 3 (UX_MODEL §5):
// dial 2 = top present GAIN/character source, dial 3 = top present AMBIENCE.
const BlockCat GAIN_BUCKET[]  = { BC_DRIVE, BC_AMP, BC_COMP };
const BlockCat SPACE_BUCKET[] = { BC_REVERB, BC_DELAY, BC_MOD, BC_FILTER, BC_PITCH };
const int GAIN_BUCKET_COUNT  = sizeof(GAIN_BUCKET) / sizeof(GAIN_BUCKET[0]);
const int SPACE_BUCKET_COUNT = sizeof(SPACE_BUCKET) / sizeof(SPACE_BUCKET[0]);

